theme: ../src

siteConfig:
  url: https://saber-theme-vuepress.netlify.com/
  author: Author of This Site
  email: author@your-domain.com
  title: Saber-Vuepress-Theme
  logo: logo.jpg
  description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.

themeConfig:
  nav: 
    - text: Home
      link: /
    - text: About
      link: /about.html
    - text: Page
      link: /page.html
    - text: Blog
      link: /blog.html
  search:
  repo:
    - site: Github
      name: askcreative

markdown:
  highlighter: prism
  plugins:
    - resolve: markdown-it-div
    - resolve: markdown-it-emoji

plugins:
  - resolve: saber-plugin-query-posts
